version: "3.7"
services:

  haproxy:
#    image: haproxy:2.0
#    image: test-haproxy-sessions_haproxy:latest
    build: haproxy
    ports:
      - "1111:1111" # nginx
      - "8080:8080"
      - "9000:9000"
    volumes:
      - ./haproxy/usr/local/etc/haproxy:/test
#    command:
#      sleep 100000

  httpbin_1:
    image: ericdahl/httpbin:e249975
    ports:
      - "8080"

  httpbin_2:
    image: ericdahl/httpbin:e249975
    ports:
      - "8080"

  nginx:
    image: nginx
    ports:
      - "80"